module.exports = {
  REPLICATE_CHUNK: 'REPLICATE_CHUNK',
  REPAIR_REPLICA: 'REPAIR_REPLICA',
  VERIFY_CHECKSUM: 'VERIFY_CHECKSUM',
  DELETE_CHUNK: 'DELETE_CHUNK',
  CLEANUP_FAILED_UPLOAD: 'CLEANUP_FAILED_UPLOAD',
  RUN_RECOVERY_CYCLE: 'RUN_RECOVERY_CYCLE',
};